In [ ]:
import cv2

In [ ]:
img = cv2.imread("galaxy.jpg", -1) # Con -1 se queda de colores, com 0 se vuelve blanco y negro
print(type(img))
print(img) # Se volvió la imagen todos los arrays con los colores en rgb de cada pixel
print(img.shape) # Muestra el número de columnas y líneas de img
print(img.ndim)

In [ ]:
cv2.imshow("Galaxy", img)
cv2.waitKey(0) # Con el cero se queda todo el tiempo que queramos abierta la imagen
cv2.destroyAllWindows()

In [ ]:
#Se puede redimensionar
resized_image = cv2.resize(img,(1000,500))
cv2.imshow("Galaxy02", resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Se puede redimensionar para que sea proporcional
import cv2

img = cv2.imread("galaxy.jpg", -1) 
print(type(img))
print(img) 
print(img.shape) 
print(img.ndim)

resized_image = cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("Galaxy02", resized_image)
cv2.imwrite("Galaxy_resized.jpg", resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


<class 'numpy.ndarray'>
[[[19 15 10]
  [23 19 14]
  [21 15  8]
  ...
  [27 22 13]
  [22 17  8]
  [23 18  9]]

 [[17 13  8]
  [21 17 12]
  [19 13  6]
  ...
  [27 22 13]
  [22 17  8]
  [24 19 10]]

 [[17 14  6]
  [18 15  7]
  [21 18 10]
  ...
  [23 16  7]
  [33 26 17]
  [30 23 14]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 5  5  5]
  [ 8  8  8]
  [14 14 14]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 2  2  2]
  [ 3  3  3]
  [ 9  9  9]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 3  3  3]]]
(1485, 990, 3)
3


In [ ]:
# Para volver blanco y negro una imagen
import cv2

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

img = cv2.imread("photo.jpg")

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow("Gray", gray_img)
cv2.waitKey(0)
cv2.destroyAllWindows()