In [3]:
import numpy
n = numpy.arange(27)

In [8]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [10]:
n2 = n
n2.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [12]:
n3 = n
n3. reshape (3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
r = numpy.asarray(
    [
    [123, 12, 123, 12, 33], 
    [], 
    []
    ], dtype = object
)
r

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)